# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: raghavendrar.bharadwaj@getronics.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        azureDNS:
          resourceGroupName: #RG Name in which DNS zone is present
          subscriptionID: #Subscription Name in which DNS zone is present
          hostedZoneName: #Name of the DNS zone
          environment: AzurePublicCloud
          managedIdentity:
            clientID: #Client ID of the Managed Identity